### PR TITLE
Add topological sorting for dumped views using TSort

### PR DESCRIPTION
**Pull request by calebhearth**
Co-authored-by: Mykhaylo Sorochan <mykhaylo.sorochan@toptal.com> 
Co-authored-by: Edward Loveall <edward@edwardloveall.com>

### CODE REVIEW

**Review by derekprior — APPROVED** [review]

**Comment by iBublik** [comment]
Hey @calebhearth, thanks for merging! Any ETA when this will be released?

**Comment by cdinger** [comment]
Should this postgres-specific code llive in the postgres adpater? I think this will break the other adapters unless they monkey-patch `Scenic::SchemaDumper` to override the postgres query and assumptions around what `Scenic.database.execute` returns.

I've started looking at this for the Oracle adapter and this is the only solution I've come up with.

**Comment by calebhearth** [comment]
No I think you're right, this should have been part of an adapter.

**Comment by derekprior** [comment]
This behavior has been moved to the adapter. cc @cdinger

**Comment by inkstak** [comment]
Hi there, any plan to release this fix ? We used a fork with the patched version for a year now.

**Pull request merged**
