### PR TITLE
Fix a couple of bugs around schema qualified view names

### PR DESCRIPTION
**Pull request by gumchum**
585ff85c5f5aee7e5ba0f5b13d806ed9fc109f20 - Fixes an issue where the generated migration for a schema qualified view name is not properly camelized.

```
$ rails g scenic:view non_public.search
      create  db/views/non_public_searches_v01.sql
      create  db/migrate/20190830220558_create_non_public_searches.rb
$ head db/migrate/20190830220558_create_non_public_searches.rb
class CreateNonPublicsearches < ActiveRecord::Migration[5.1]
  def change
    create_view "non_public.searches"
  end
end
```

The generated class name should be `CreateNonPublicSearches` instead of `CreateNonPublicsearches`.

585ff85c5f5aee7e5ba0f5b13d806ed9fc109f20 - Fixes an issue where, having generated a scenic view for a schema qualified view and editing its view definition, running `rake db:migrate` fails to find the view definition.

```
$ rails g scenic:view non_public.search
      create  db/views/non_public_searches_v01.sql
      create  db/migrate/20190830220558_create_non_public_searches.rb
$ vim db/views/non_public_searches_v01.sql
$ bundle exec rake db:migrate
== 20190830220558 CreateNonPublicSearches: migrating ==========================
-- create_view("non_public.searches")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No such file or directory @ rb_sysopen - /Users/brianchhun/.../db/views/non_public.searches_v01.sql
/Users/brianchhun/.../db/migrate/20190830220558_create_non_public_searches.rb:3:in `change'
/Users/brianchhun/.rbenv/versions/2.4.3/bin/bundle:23:in `load'
/Users/brianchhun/.rbenv/versions/2.4.3/bin/bundle:23:in `<main>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/brianchhun/.../db/views/non_public.searches_v01.sql
/Users/brianchhun/.../db/migrate/20190830220558_create_non_public_searches.rb:3:in `change'
/Users/brianchhun/.rbenv/versions/2.4.3/bin/bundle:23:in `load'
/Users/brianchhun/.rbenv/versions/2.4.3/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by Kooshaba** [comment]
This seems like it is working to me. Just tested on my project with no problems. Could someone merge this in?

**Comment by calebthompson** [comment]
Resolves #280

**Comment by gumchum** [comment]
I'm not familiar with the contribution guidelines, but is there anything else that's needed to get this merged in?

**Comment by mingan** [comment]
This is a pretty drastic change that breaks our migrations. We have a series of view definitions with file names in the form `schema.view_name_v[..].sql` and suddenly we can't migrate. I guess it's ok for newly created versions but the existing definition files should remain readable. (Or at least some heads up in the changelog would have been nice.)

**Pull request merged**
