### PR TITLE
Configurable root path

### PR DESCRIPTION
**Pull request by tomasc**
This PR allows for configuration of the root path, where Scenic looks up its views:

```ruby
Scenic.configure do |config|
  config.root_path = MyEngine.root
end
```

The default value stays `Rails.root`.

This is a follow up to https://github.com/scenic-views/scenic/pull/237#issuecomment-513880655 and addresses #261.

### CODE REVIEW

**Comment by derekprior** [comment]
@tomasc how would this work in cases where both the engine and the app itself want to use Scenic?

**Comment by trevorrjohn** [comment]
I would think you need two config files for that, one in the engine and one at the app level. Or you could add a env var or argument to override the "default" path.

**Comment by derekprior** [comment]
The configuration is currently a singleton, so I don't think that would work

**Comment by derekprior** [comment]
We have a number of proposed changes (see: https://github.com/scenic-views/scenic/labels/view-paths) that cover this same functionality. I think https://github.com/scenic-views/scenic/pull/237 is closest to something we would consider merging in that covers multiple use cases. Swapping one static path for another would solve some problems but create others.

**Pull request closed without merging**
